Repository CoVPN/correlates_reporting, pull requests merged in 2021-05, with the labels that each got.

#300 Travis deploy for simultaneous report building
  .travis.yml
  _deploy_reports.sh
Labels: enhancement

#298 Adding tests
  Makefile
  data_clean/make_clean_dat_check.R
  data_clean/make_dat_proc.R
  data_clean/make_raw_dat_check.R
  data_raw/README.md
Labels: enhancement

#313 update wrcdf plot to handle 0-width CIs
  cor_graphical/code/cor_wrcdf_plot_function.R
Labels: bug

#312 Data clean 20210512
  data_clean/verification/verification_code/process_data_raw.R
  data_clean/verification/verification_report.Rmd
  data_clean/verification/verification_report.pdf
Labels: verification

#316 simplify stochastic CoP
  _bookdown_cop.yml
  _common.R
  cop_stochastic/code/make_sve_cop_figs.R
  cop_stochastic/code/params.R
  cop_stochastic/code/run_cop_analysis.R
  cop_stochastic/code/sl_lrnr_libs.R
  cop_stochastic/report.Rmd
  index_cop.Rmd
  renv.lock
Labels: enhancement

#326 cor graphical fixes with file naming
  cor_graphical/code/CoR_assay_graphics.R
  cor_graphical/code/CoR_wrcdf_with_VE_lines.R
  cor_graphical/code/cor_graphics_violin_scatter.R
  cor_graphical/code/params.R
Labels: bug
