Repository CoVPN/correlates_reporting, pull requests merged in 2021-03, with the labels that each got.

#117 Reporting improvements
  CONTRIBUTING.md
  DESCRIPTION
  README.md
  _bookdown_cop.yml
  _bookdown_cor.yml
  _bookdown_immuno.yml
  _build.sh
  _common.R
  _deploy_reports.sh
  aws_build_instructions.md
  index_cop.Rmd
  index_cor.Rmd
  index_immuno.Rmd
Labels: enhancement

#130 improving Travis build commit messages
  _deploy_reports.sh
Labels: documentation, enhancement

#132 Add GPL-3 License
  .Rbuildignore
  DESCRIPTION
  LICENSE.md
  README.md
  cor_threshold/code/old_code/Threshold_searching_analysis.R
Labels: documentation

#133 include texlive and pandoc in AWS build instructions
  aws_build_instructions.md
Labels: documentation

#135 Fix recent issues with CoR graphs
  cor_graphical/code/CoR_assay_graphics.R
  cor_graphical/code/cor_data_preprocess.R
  cor_graphical/code/covid_corr_plot_functions.R
Labels: bug, enhancement

#166 Update rcdf
  cor_graphical/code/covid_corr_plot_functions.R
  immuno_graphical/code/covid_corr_plot_functions.R
  immuno_graphical/code/descriptive_graphics_data_preprocess.R
  immuno_graphical/code/descriptive_graphics_two_phase_plots.R
  immuno_graphical/verification/verification_statistics.Rmd
  renv/activate.R
Labels: enhancement

#161 Removing Live virus endpoints
  _common.R
  immuno_tabular/code/make_clean_data.R
  immuno_tabular/code/make_functions.R
  immuno_tabular/code/make_parameters.R
  immuno_tabular/code/make_table_all.R
  immuno_tabular/report.Rmd
  immuno_tabular/verification/table_specifications.md
Labels: bug

#168 fix response rate and format labels in figures
  cor_graphical/code/cor_data_preprocess.R
  cor_graphical/code/cor_graphics_violin_scatter.R
Labels: enhancement

#167 Fixed `TwophasesampInd` and weights for threshold `Day29` analysis
  cor_threshold/code/Run_Threshold_analysis.R
  cor_threshold/code/clean_data.R
  cor_threshold/code/params.R
  cor_threshold/code/tmleThresh.R
Labels: bug

#158 reporting adjustments and figure placement
  .travis.yml
  DESCRIPTION
  _common.R
  _output.yml
  cor_coxph/Makefile
  cor_coxph/code/cor_coxph.R
  cor_coxph/code/params.R
  cor_graphical/report.Rmd
  css/center.css
  css/style.css
  css/toc.css
  index_cop.Rmd
  index_cor.Rmd
  index_immuno.Rmd
  latex/krantz.cls
  latex/preamble.tex
  renv.lock
  renv/activate.R
Labels: enhancement

#183 fix errors in the pair plots
  immuno_graphical/code/ggally_cor_resample.R
  immuno_graphical/verification/verification_statistics.Rmd
  immuno_graphical/verification/verification_statistics.html
Labels: bug

#182 update shared `renv` library
  immuno_graphical/code/covid_corr_plot_functions.R
  renv.lock
Labels: enhancement

#193 Fixing page layouts
  _common.R
  _output.yml
  base_riskscore/.gitignore
  cor_graphical/report.Rmd
  cor_tabular/Makefile
  cor_tabular/README.md
  cor_tabular/header.tex
  cor_tabular/report.Rmd
  cor_threshold/report.Rmd
  cor_threshold/sub_report.Rmd
  immuno_graphical/report.Rmd
  immuno_tabular/report.Rmd
  latex/preamble.tex
Labels: enhancement

#160 risk score integration
  .gitignore
  .travis.yml
  Makefile
  _bookdown_riskscore.yml
  _deploy_reports.sh
  _report_riskscore/.gitkeep
  base_riskscore/Makefile
  base_riskscore/code/append_risk_score_to_data.R
  base_riskscore/code/constructSL_predict_on_vaccine.R
  base_riskscore/code/constructSL_predict_on_vaccine.sh
  base_riskscore/code/createRDAfiles_fromSLobjects.R
  base_riskscore/code/createRDAfiles_fromSLobjects.sh
  base_riskscore/code/get_SLweights_Modelpredictors.R
  base_riskscore/code/get_SLweights_Modelpredictors.sh
  base_riskscore/code/run_cvsl_riskscore.R
  base_riskscore/code/run_cvsl_riskscore.sh
  base_riskscore/code/sl_screens.R
  base_riskscore/code/submit_cluster_job.sh
  base_riskscore/code/tables_figures.R
  base_riskscore/code/tables_figures.sh
  base_riskscore/code/utils.R
  base_riskscore/report.Rmd
  base_riskscore/report_sub.Rmd
  base_riskscore/results/.gitkeep
  covpn_correlates.Rproj
  index_riskscore.Rmd
  renv.lock
Labels: enhancement
