Repository CoVPN/correlates_reporting, pull requests merged in 2021-06, with the labels that each got.

#363 Fix `_deploy_reports.sh`
  .travis.yml
  _deploy_reports.sh
  config.yml
Labels: bug

#51 Super Learner baseline risk score verification
  .travis.yml
  base_riskscore/verification/.here
  base_riskscore/verification/Makefile
  base_riskscore/verification/README.md
  base_riskscore/verification/validation_plan.Rmd
  base_riskscore/verification/verification_code/.gitignore
  base_riskscore/verification/verification_code/.here
  base_riskscore/verification/verification_code/Makefile
  base_riskscore/verification/verification_code/code/data_prep.R
  base_riskscore/verification/verification_code/code/fit_cv_superlearner.R
  base_riskscore/verification/verification_code/code/fit_superlearner.R
  base_riskscore/verification/verification_code/code/get_cv_sl_seeds.R
  base_riskscore/verification/verification_code/code/get_cvauc.R
  base_riskscore/verification/verification_code/code/get_risk_scores.R
  base_riskscore/verification/verification_code/code/sl_screen_fn.R
  base_riskscore/verification/verification_code/code/submit_jobs.sh
  base_riskscore/verification/verification_code/code/submit_jobs_local.sh
  base_riskscore/verification/verification_code/code/superlearner_library.R
  base_riskscore/verification/verification_code/data_clean/.gitkeep
  base_riskscore/verification/verification_code/output/.gitkeep
  base_riskscore/verification/verification_code/report.Rmd
  base_riskscore/verification/verification_report.Rmd
  base_riskscore/verification/verification_report.pdf
  renv.lock
Labels: documentation, verification

#404 Updating `Matrix` and `kyotil` in `renv` library
  renv.lock
  renv/activate.R
Labels: enhancement

#398 Triggering Ensemble builds on travis
  .travis.yml
  _bookdown_cop.yml
  _bookdown_cor.yml
  _bookdown_immuno.yml
  _bookdown_riskscore.yml
  _build.sh
  config.yml
Labels: enhancement
